# Generated by Django 3.0.8 on 2020-07-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('current_bid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_URL', models.URLField()),
                ('listed_datetime', models.DateTimeField(verbose_name='date listed')),
            ],
        ),
    ]
