# Generated by Django 3.0.8 on 2020-07-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='does it have internet?'),
            preserve_default=False,
        ),
    ]
