# Generated by Django 3.0.8 on 2020-07-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_URL',
            field=models.URLField(blank=True),
        ),
    ]
