# Generated by Django 3.0.8 on 2020-07-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('FN', 'Fashion, Clothing & Accessories'), ('HB', 'Health & Beauty'), ('TY', 'Toys & Baby Equipment'), ('BK', 'Books, Vinyl and Other Physical Media'), ('FD', 'Groceries, Food and Drinks'), ('TK', 'Technology including Phones and Laptops'), ('HM', 'Home and Furniture'), ('GF', 'Flowers and Gifts'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
