# Generated by Django 3.0.8 on 2020-07-31 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
