# Generated by Django 3.0.8 on 2020-07-31 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_watchlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'listing')},
        ),
    ]
